# 
# This source file is part of the Apodini AsyncHTTPClient open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

module: ApodiniAsyncHTTPClient
author: Paul Schmiedmayer
theme: fullwidth
output: ./docs
documentation: ./*.md
author_url: https://github.com/Apodini
github_url: https://github.com/Apodini/ApodiniAsyncHTTPClient
